---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  ## Create ansible.cfg with correct roles_path
  #- printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic scripts syntax check
  - bash -n functions/*
  # RC syntax check and load
  - bash -n ./ansible-tools.rc && . ./ansible-tools.rc

---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

language: python

python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Check bash version
  - bash --version
  # Install ansible
  - pip install ansible; ansible --version
  ## Create ansible.cfg with correct roles_path
  #- printf '[defaults]\nroles_path=../' >ansible.cfg

# Run
script:

  - bash -Cu .tests.sh

  # Basic scripts syntax check
  - |
    for s in functions/*; do bash -n "${s}" || exit 1; done
  # RC syntax check and load
  - bash -n ./ansible-tools.rc && . ./ansible-tools.rc

# Notifications
#notifications:
#  email:
#  - your@emailaddress

