---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

language: python

python: "3.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Check bash version
  - bash --version
  # Install ansible
  - pip install ansible; ansible --version

# Run
script:

  - bash -Cu .tests.sh

# Notifications
#notifications:
#  email:
#  - your@emailaddress

