#!/bin/bash
THIS="${0##*/}"
BASE="${THIS%.*}"
CDIR=$([ -n "${0%/*}" ] && cd "${0%/*}" 2>/dev/null; pwd)

. $CDIR/ansible-tools.rc $@ ||
  exit 127

AT_AUTHOR="${AT_AUTHOR:-ansible@localhost}"
AT_COMPANY="${AT_COMPANY:-ANSIBLE.COM}"

ROLENAME=""
ROLEPATH="${ROLEPATH:-.}"
TMPLTDIR="${TMPLTDIR:-$CDIR/${BASE}.d}"

while [ $# -gt 0 ]
do
  case "$1" in
  -p)
    if [ -z "$ROLEPATH" ] &&
       [ -d "$2" ]
    then
      ROLEPATH="$2"
    fi
    shift
    ;;
  -*)
    ;;
  *)
    ROLENAME="$1"
    ;;
  esac
  shift
done

[ -z "$ROLENAME" ] && {
  cat <<_USAGE_
Usage: $THIS ROLENAME [-p ROLEPATH]

_USAGE_
  exit 1
}
[ ! -d "$ROLEPATH" ] && {
  echo "$THIS: no such directry '$ROLEPATH'" 1>&2
  exit 1
}
[ -d "$ROLEPATH/$ROLENAME" ] && {
  echo "$THIS: '$ROLENAME' found in '$ROLEPATH'." 1>&2
  exit 1
}

ansible-galaxy init --offline -p $ROLEPATH $ROLENAME && {

  ROLE_DIR="$ROLEPATH/$ROLENAME"

  if [ -e "$ROLE_DIR/meta/main.yml" ]
  then
    cat "$ROLE_DIR/meta/main.yml" |
    sed -e 's#\(author:\) \(your name\)#\1 '"$AT_AUTHOR"'#g' \
        -e 's#\(company:\) \(your company (optional)\)#\1 '"$AT_COMPANY"'#g' \
        1>.temp 2>/dev/null &&
    mv -f .temp \
          "$ROLE_DIR/meta/main.yml" \
          1>/dev/null 2>&1
  fi
  
  if [ -d "$TMPLTDIR" ]
  then
    cp -fLRv "$TMPLTDIR/"* \
             "$ROLE_DIR/"
  fi

}

exit $?
