#!/bin/bash
THIS="${0##*/}"
BASE="${THIS%.*}"
CDIR=$([ -n "${0%/*}" ] && cd "${0%/*}" 2>/dev/null; pwd)

. $CDIR/ansible-tools.rc $@ || 
  exit 127

targ_host=""
inventory=""
temp_file="$(mktemp -u /tmp/hosts.XXXXXXXX)"

ansible_opts=""

_cleanup() {
  rm -f "$temp_file" 1>/dev/null 2>&1
  return 0
}

trap -- "_cleanup" EXIT SIGTERM SIGINT SIGHUP SIGQUIT

while [ $# -gt 0 ]
do
  case "$1" in
  -i)
    inventory="$2"
    shift
    ;;
  --inventory-file=*)
    inventory=$(echo -- "$2"|cut -d= -f2)
    ;;
  -m)
    shift
    ;;
  --module-name=*)
    ;;
  -*)
    ansible_opts="${ansible_opts} $1"
    ;;
  *)
    if [ -z "${targ_host}" ]
    then
      targ_host="$1"
    else
      ansible_opts="${ansible_opts} $1"
    fi
    ;;
  esac
  shift
done

[ -z "${targ_host}" ] && {
  cat <<_USAGE_
Usage: $THIS [ansible_opts] hostname_or_ipaddress

_USAGE_
  exit 1
}

[ -e "${inventory}" ] || {
  inventory="${temp_file}"
  echo "${targ_host}" >"${inventory}"
}

( cd "$CDIR" 1>/dev/null 2>&1;
  ansible -m setup -i ${inventory} "${targ_host}" $ansible_opts )

exit $?
