---
# platform.yml

- block:

  - name: platform | Set Facts platform
    set_fact:
      __os_family: "{{ ansible_os_family if test_run|d(false) == false else 'Test' }}"
      __distribution: "{{ ansible_distribution if test_run|d(false) == false else 'Test' }}"
    when: __os_family is not defined
          or __distribution is not defined

  - name: platform | Check the Platform.
    fail:
      msg: |
       You can not perform the task in this platform: OS-Family '{{ __os_family }}', Distribution '{{ __distribution }}'."
    when: ( __os_family is not none
            and platform_allow_os_families|d(none) is not none
            and __os_family not in platform_allow_os_families )
          or ( __distribution is not none
               and platform_allow_distributions|d(none) is not none
               and __distribution not in platform_allow_distributions )

  when: ( platform_allow_os_familys|d(none) is iterable
          and platform_allow_os_familys|d(none) is not string )
        or ( platform_allow_distributions|d(none) is iterable
             and platform_allow_distributions|d(none) is not string )
  tags:
  - always

